import path from "path";
import { AnalysisShotType } from "./types";

export type SfxPreset = {
  id: string;
  filePath: string;
  keywords: string[];
  shotTypes: AnalysisShotType[];
  volume: number;
  offsetSec: number;
  trimToSec: number;
  fallbackWeight?: number;
};

const BGM_DIR = path.join(process.cwd(), "storage", "bgm");

export const SFX_PRESETS: SfxPreset[] = [
  {
    id: "meat-sizzle",
    filePath: path.join(BGM_DIR, "베이컨굽는소리.mp3"),
    keywords: [
      "고기",
      "불판",
      "굽는",
      "구워",
      "육즙",
      "스테이크",
      "갈비",
      "삼겹",
      "바베큐",
      "오븐",
      "화덕",
      "튀김",
      "튀김기",
      "갓 나온",
      "막 나온",
      "베이컨",
    ],
    shotTypes: ["food_hook", "food_detail"],
    volume: 1.2,
    offsetSec: 0.06,
    trimToSec: 1.2,
    fallbackWeight: 0.9,
  },
  {
    id: "water-pour",
    filePath: path.join(BGM_DIR, "물따르는소리.MP3"),
    keywords: [
      "따르는",
      "따르",
      "붓는",
      "붓",
      "음료",
      "커피",
      "라떼",
      "에이드",
      "소스",
      "국물",
      "육수",
    ],
    shotTypes: ["food_hook", "food_detail"],
    volume: 1.05,
    offsetSec: 0.08,
    trimToSec: 1.0,
    fallbackWeight: 0.78,
  },
  {
    id: "ice",
    filePath: path.join(BGM_DIR, "얼음소리.MP3"),
    keywords: ["얼음", "아이스", "차가운", "컵", "잔", "콜드", "시원"],
    shotTypes: ["food_hook", "food_detail"],
    volume: 1.0,
    offsetSec: 0.04,
    trimToSec: 0.9,
    fallbackWeight: 0.55,
  },
  {
    id: "bread-cut",
    filePath: path.join(BGM_DIR, "빵자르는소리.mp3"),
    keywords: [
      "자르는",
      "자르기",
      "잘라",
      "썰기",
      "썰어",
      "컷팅",
      "칼질",
      "도우",
      "갈라",
      "갈라지는",
      "뜯는",
      "뜯어",
      "들어올려",
      "들어 올려",
      "늘어나는",
      "늘어남",
      "치즈 스트레치",
      "피자",
      "빵",
    ],
    shotTypes: ["food_hook", "food_detail"],
    volume: 1.12,
    offsetSec: 0.05,
    trimToSec: 1.0,
    fallbackWeight: 0.96,
  },
  {
    id: "crunch-bite",
    filePath: path.join(BGM_DIR, "과자씹는소리.mp3"),
    keywords: [
      "씹는",
      "한입",
      "한 입",
      "먹는",
      "먹자마자",
      "바삭",
      "크리스피",
      "튀김",
      "치킨",
      "감자튀김",
      "과자",
    ],
    shotTypes: ["food_hook", "food_detail", "ending"],
    volume: 1.08,
    offsetSec: 0.08,
    trimToSec: 0.95,
    fallbackWeight: 0.88,
  },
  {
    id: "boiling",
    filePath: path.join(BGM_DIR, "끓이는소리.mp3"),
    keywords: [
      "끓는",
      "끓여",
      "보글",
      "보글거리는",
      "국물",
      "탕",
      "찌개",
      "라면",
      "스프",
      "소스",
    ],
    shotTypes: ["food_hook", "food_detail"],
    volume: 1.08,
    offsetSec: 0.05,
    trimToSec: 1.0,
    fallbackWeight: 0.7,
  },
  {
    id: "board-slice",
    filePath: path.join(BGM_DIR, "도마에서 써는소리.mp3"),
    keywords: [
      "도마",
      "써는",
      "썰기",
      "썰어",
      "칼질",
      "컷팅",
      "자르는",
      "손질",
      "슬라이스",
    ],
    shotTypes: ["food_detail"],
    volume: 1.0,
    offsetSec: 0.03,
    trimToSec: 0.95,
    fallbackWeight: 0.74,
  },
  {
    id: "eat-pop",
    filePath: path.join(BGM_DIR, "먹는효과음.mp3"),
    keywords: ["먹는", "먹자마자", "한입", "한 입", "시식", "맛보는"],
    shotTypes: ["food_hook", "food_detail", "ending"],
    volume: 1.02,
    offsetSec: 0.05,
    trimToSec: 0.65,
    fallbackWeight: 0.72,
  },
  {
    id: "cereal-pour",
    filePath: path.join(BGM_DIR, "시리얼붓는소리.mp3"),
    keywords: [
      "시리얼",
      "붓는",
      "붓기",
      "쏟는",
      "토핑",
      "올리는",
      "올려",
      "뿌리는",
    ],
    shotTypes: ["food_hook", "food_detail"],
    volume: 0.96,
    offsetSec: 0.04,
    trimToSec: 0.8,
    fallbackWeight: 0.62,
  },
  {
    id: "bite-soft",
    filePath: path.join(BGM_DIR, "씹는소리.mp3"),
    keywords: ["씹는", "먹는", "한입", "한 입", "쫀득", "촉촉"],
    shotTypes: ["food_hook", "food_detail", "ending"],
    volume: 1.0,
    offsetSec: 0.07,
    trimToSec: 0.85,
    fallbackWeight: 0.76,
  },
  {
    id: "crunch-hit",
    filePath: path.join(BGM_DIR, "크런치.mp3"),
    keywords: [
      "크런치",
      "바삭",
      "와삭",
      "바사삭",
      "깨는",
      "깨트",
      "깨뜨",
      "부수는",
      "부숴",
      "코팅",
      "설탕 코팅",
      "크러스트",
    ],
    shotTypes: ["food_hook", "food_detail", "ending"],
    volume: 1.08,
    offsetSec: 0.04,
    trimToSec: 0.72,
    fallbackWeight: 0.93,
  },
  {
    id: "oven-ding",
    filePath: path.join(BGM_DIR, "오븐띵.mp3"),
    keywords: ["오븐", "갓 나온", "막 나온", "완성", "서빙", "준비"],
    shotTypes: ["food_hook", "food_detail", "ending"],
    volume: 0.94,
    offsetSec: 0.02,
    trimToSec: 0.6,
    fallbackWeight: 0.58,
  },
];
